### ISSUE TITLE
Swift 3 problems

### ISSUE THREAD

**Issue by Stengo** [Liquidsoul/XCTestPlayground#7]
The current Swift 3 branch unfortunately does not work for me in Xcode 8.

On the positive side it seems to be an easy fix. I replaced `Boolean` with `Bool`, `self.dynamicType` with `type(of: self)` and made `XCTestCase` `open`.
At least for my sample project that was enough to make it work again.

**Comment by Liquidsoul** [comment]
Thank you for reporting this!
I pushed a fix in branch `swift3` 707086a367b6fe7059408933c3374cc73db59077
I think it may be time to merge to master 😄
